squirrel_proj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
        path('', include('squirrels.urls')),
        path('admin/', admin.site.urls),
]#+ static(
#    settings.MEDIA_URL,
#    document_root=settings.MEDIA_ROOT,
#) + static(
#    settings.STATIC_URL,
#    document_root=settings.STATIC_ROOT,
#)

squirrels/urls.py
from django.urls import path

from . import views

app_name = 'squirrels'

urlpatterns = [
   # path('', views.index, name='index'),
    path('map/', views.map, name='map'),
    path('sightings/', views.sightings, name='sightings'),
    path('sightings/add/', views.add, name='add'),
    path('sightings/stats/', views.stats, name='stats'),
    path('sightings/<squirrel_id>/', views.unique, name='unique')
]

squirrels/models.py
from django.db import models
from django.utils.translation import gettext as _


class Squirrel(models.Model):

    unique_id = models.CharField(
           max_length=20,
           null=True
    )
   
    latitude = models.DecimalField(
            max_digits=17,
            decimal_places=15,
            null=True,
    )

    longitude = models.DecimalField(
            max_digits=17,
            decimal_places=15,
            null=True,
    ) 

    AM = 'AM'
    PM = 'PM'

    SHIFT_CHOICES = [
            (AM, _('AM')),
            (PM, _('PM')),

    ]

    shift = models.CharField(
            max_length=20,
            choices=SHIFT_CHOICES,
            default=AM,
    )
    
    ADULT = 'Adult'
    JUVENILE = 'Juvenile'
    QUESTION = '?'

    AGE_CHOICES = [
            (ADULT, _('Adult')),
            (JUVENILE, _('Juvenile')),
            (QUESTION, _('?')),
    ]

    age = models.CharField(
            max_length=20,
            choices=AGE_CHOICES,
            default=ADULT,
    )

    date = models.DateField( 
        null=True,
    )
    
    def  __str__(self):
        return self.unique_id

squirrels/forms.py
from django.forms import ModelForm

from .models import Squirrel

class AddSightingsForm(ModelForm):
    class Meta:
        model  = Squirrel
        fields  = [
            'latitude',
            'longitude',
            'unique_id',
            'shift',
            'age',
            'date',
        ]

squirrels/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.http import HttpResponseRedirect

from .models import Squirrel
from django.db.models import Avg

from .forms import AddSightingsForm


def map(request) :
    squirrels = Squirrel.objects.all()[:100]
    context = {
            'squirrels': squirrels
            }
    return render(request, 'map/index.html', context)

def sightings(request):
    squirrels = Squirrel.objects.all()
    context={
        'squirrels': squirrels
        }

    return render (request, 'sightings/main.html', context)

def unique(request, squirrel_id):
    squirrel = get_object_or_404(Squirrel, unique_id=squirrel_id)
    if request.method == 'POST':
        form = AddSightingsForm(request.POST, instance=squirrel)
        if  form.is_valid():
            updated_form = form.save()
            return HttpResponseRedirect('/sightings/')
    else:
        form = AddSightingsForm(instance=squirrel)
    
    context  = {
        'squirrel':squirrel,
        'form':form
        }

    return render(request, 'sightings/unique.html',context)

def add(request):
    if request.method == 'POST':
        form =AddSightingsForm(request.POST)
        if  form.is_valid():
            form.save()
            return HttpResponseRedirect('/sightings/')
    else:
        form = AddSightingsForm()
    return render(request, 'sightings/add.html', {'form':form})



def  stats(request):
    total_sightings = Squirrel.objects.count()
    adults = Squirrel.objects.filter(age='Adult').count()
    juveniles = Squirrel.objects.filter(age='Juvenile').count()
    shifts = Squirrel.objects.filter(shift='AM').count()
    latitude = Squirrel.objects.aggregate(Avg('latitude'))
    longitude = Squirrel.objects.aggregate(Avg('longitude'))

    context={
            'total_sightings': total_sightings,
            'adults' :adults,
            'juveniles':juveniles,
            'shifts': shifts,
            'latitude':latitude,
            'longitude':longitude
        }
    return render(request, 'sightings/stats.html',context)

squirrels/templates/map/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin=""></script>

    <style>
      html,body {
        height: 100%;
      }
    </style>
  </head>
  <body>
    <div id="map" class="container-fluid h-100"></div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Leaflet JS -->
    <script>
        var map_center = [
            40.782091,  // Latitude
            -73.964285  // Longitude
        ];
        var zoom_level = 14;
        var map = L.map('map').setView(map_center, zoom_level);
        L.tileLayer('https://{server}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            server: 'a',  // can be 'a', 'b', or 'c'
            // must leave attribution in!
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
        }).addTo(map);

        <!-- L.Icon.Default.prototype.options.iconSize = 15; -->
        <!-- L.Icon.Default.prototype.options.iconAnchor = [0, 0]; -->
        <!-- L.Icon.Default.prototype.options.shadowSize = 15; -->
        <!-- L.Icon.Default.prototype.options.shadowAnchor = [0, 0]; -->

        {% for squirrel in squirrels %}
        
	 var point_lat_lon = [{{ squirrel.latitude }}, {{ squirrel.longitude }}];
	 var marker = L.marker(point_lat_lon).addTo(map);

	{% endfor %}

    </script>
  </body>
</html>		

squirrels/templates/sightings/add.html
<!doctype html>
<html lang="en">
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<form  action="/sightings/add/"  method="post">
 <div class="form-group">
	 <label for="/sightings/add/"> Please input your new squirrel sighting information below! </label><br>
   	 {% csrf_token %}
	 {% for field in form %}
	<div >
		   <label class="col-sm-2 col-form-label">{{field.label}}</label>
	<div class="col-sm-10"> 
	    {{ field }}
	</div>
	   </div>
	{% endfor %}
	<br>
     <div class="col-auto">
    <input type="submit" value="Submit">
    </div>
   </div>
</form>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

squirrels/templates/sightings/main.html
<!doctype html>
<html lang=“en”>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<meta charset=utf-8> 
	<title>Squirrel Sightings Page</title>
</head> 
<body> 
<button type="button" class="btn btn-success btn-lg">
<a href="add/" style="color:inherit">Add New Squirrel Sighting </a>
</button>
<button type="button" class="btn btn-success btn-lg">
<a href="/map/" style="color:inherit">Squirrel Sighting Map </a>
</button>
<br><br>
	
<table class="table table-striped table-responsive-md btn-table">

  <thead>
    <tr>
      <th>Squirrel ID</th>
      <th>Sighting Date</th>
      <th>Sighting Details</th>
    </tr>
  </thead>

  <tbody>
    {% for Squirrel in squirrels %}
    <tr>
	<td>{{ Squirrel.unique_id }}</td>
	<td>{{ Squirrel.date }}</td>
	<td>
		<a href="{%url 'squirrels:unique' Squirrel.unique_id %}" class="btn btn-outline-success" role="button">See Details</a>
      </td>
	</tr>
	{% endfor %}
  </tbody>

</table>	
	 
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html> 

squirrels/templates/sightings/stats.html
<html>
	<body>
		Total Number of Sightings: {{ total_sightings }} <br>
		Total Number of Adult Squirrels: {{ adults }} <br>
		Total Number of Juvenile Squirrels: {{ juveniles }} <br>
		Total Number of Squirrels seen in the morning: {{ shifts }} <br>
		Average Latitude:  {{ latitude.latitude__avg }} <br>
		Average Longitude:  {{ longitude.longitude__avg }} <br>
	</body>
</html>

squirrels/templates/sightings/unique.html
<html>
	 <body>
            Latitude: {{ squirrel.latitude  }} <br>
            Longitude: {{ squirrel.longitude  }} <br>
            Unique ID:  {{ squirrel.unique_id  }} <br>
            Shift: {{ squirrel.shift  }} <br>
            Date: {{ squirrel.date  }} <br>
	    Age: {{ squirrel.age }} <br><br>


	    <form  action="{%url 'squirrels:unique' squirrel.unique_id %}"  method="post">
		<label for="{%url 'squirrels:unique' squirrel.unique_id %}"> Update Sighting: </label><br>
    		
	{% csrf_token %}
            {% for field in form %}
	    {{field.label}}
            {{ field }} <br>
        {% endfor %}

		<input type="submit" value="Submit">
 	</form>	

	 </body>
</html>